# Generated by Django 5.0.2 on 2024-07-17 14:20

from django.db import migrations


def create_categories(apps, schema_editor):
    Category = apps.get_model('ui', 'Category')
    categories = [
        'Breakfast',
        'Lunch',
        'Dinner',
        'Snacks',
        'Drinks',
        'Desserts',
    ]
    for category_name in categories:
        Category.objects.create(name=category_name)


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_menu'),
    ]

    operations = [
        migrations.RunPython(create_categories),
    ]
