# Generated by Django 5.0.2 on 2024-07-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_auto_20240717_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
